### ISSUE TITLE
A simple query is giving "Invalid path" error

### ISSUE THREAD

**Issue by gajus** [sanack/node-jq#103]
I have tried to query `.paths["/movie/{movie_id}"].get.responses["200"].schema` and got error "Invalid path". As far as I can tell, that is a valid query.

**Comment by gajus** [comment]
I read "Invalid query" what was "Invalid path".

This wrapper does not accept JSON as the second parameter.

**Comment by davesnx** [comment]
Hey @gajus,

You might want to take a look into options? You can pass the JSON at would be the second parameter on the jq cli. Given a `{input: 'json'}` you can pass the JSON as a second parameter.

**Comment by gajus** [comment]
> This wrapper does not accept JSON as the second parameter.

My mistake. You are right @davesnx. Thank you.
