### ISSUE TITLE
Add regex support

### ISSUE THREAD

**Issue by dspigarelli** [sanack/node-jq#108]
When I try to use a regex expression, I get the following error:

`
    jq was compiled without ONIGURUMA regex libary. match/test/sub and related functions are not available
`

Is adding regex support on the roadmap?

**Comment by davesnx** [comment]
We might consider adding match probably to jq. As I explained in another issue you can still add addons into jq.  [https://github.com/sanack/node-jq/issues/104#issuecomment-330990268](https://github.com/sanack/node-jq/issues/104#issuecomment-330990268)

**Comment by davesnx** [comment]
@dspigarelli Looks like the issue it has been open for a while and there's a workaround for it, did you manage to fix it?

I will close the issue if it's the case

**Comment by ericlewis** [comment]
fyi, this is fixed in the #150

**Comment by davesnx** [comment]
This issue is fixed already, thanks!
