### ISSUE TITLE
Add command line args as an option

### ISSUE THREAD

**Issue by Yugloocamai** [sanack/node-jq#109]
It would be nice to be able to pass something like -c to jq
`jq -c '.[]' file.json`
Maybe add 'commandLineOptions' to the available options, and append them to JQ_PATH in command.js?

**Comment by mackermans** [comment]
@Yugloocamai For the example you specified, I believe `jq.run('.[]', 'file.json', { output: 'string' })` would do the trick.

Do you have additional command line options you would like to see implemented?

**Comment by tlhunter** [comment]
@mackermans The `--sort-keys` flag is one I'd like to see implemented.

**Comment by mackermans** [comment]
Closing this issue as the original request has been resolved.
