### ISSUE TITLE
Catch cannot iterate over null error

### ISSUE THREAD

**Issue by darweshsinghcgi** [sanack/node-jq#122]
Is there a way to catch the very specific `jq: error (at <unknown>): Cannot iterate over null (null)`? I'm retrieving data from a remote location that may/may not be populated (hence it being null). I essentially want to retry but I don't know how to catch that error.

Thanks!

**Comment by davesnx** [comment]
Hey @darweshsinghcgi 

Could you share the json and the query that you are using?

**Comment by davesnx** [comment]
Given this code:

```js
const jq = require('node-jq')
const service = {
  'body': {
    'status': {
      'loadBalancer': {
        'ingress': [{ 'ip': '1.1.1.1' }]
      }
    }
  }
}

jq.run('.body.status.loadBalancer.ingress[]', service, { input: 'json' }).then(console.log)
```

Works fine, If there's no item in the array `"ingress"` will return null without throwing. If there's no `"ingress"` you might need a better jq filter using [`select`](https://stedolan.github.io/jq/manual/#select(boolean_expression))

I didn't test it, but something like that would make your use case.

```bash
"'.body.status.loadBalancer | select(ingress != null) | ingress[].ip'
```

I'm closing this since isn't an issue with node-jq itself.

Thanks for asking tho!

**Comment by darweshsinghcgi** [comment]
Thanks for the pointer. I'm still having trouble, and I've tried a few options:

```
jq.run('.body.status.loadBalancer | select(ingress != null) | ingress[].ip', service, { input: 'json' }).then((output) => {console.log(output)})
```

throws
```
jq: error: ingress/0 is not defined at <top-level>, line 1:
```

For reference, here's what the json looks like:

```
{
  "statusCode": 200,
  "body": {
    "kind": "",
    "apiVersion": "",
    "metadata": {
      "name": "",
      "namespace": "",
      "selfLink": "",
      "uid": "",
      "resourceVersion": "",
      "creationTimestamp": "",
      "labels": {
        "stripe_id": "",
        "user_id": ""
      }
    },
    "spec": {
      "ports": [
        {
          "protocol": "",
          "port": ,
          "targetPort": ,
          "nodePort": 
        }
      ],
      "selector": {
        "app_id": "",
        "auth0": "",
        "stripe": ""
      },
      "clusterIP": "",
      "type": "",
      "sessionAffinity": "",
      "externalTrafficPolicy": ""
    },
    "status": {
      "loadBalancer": {}
    }
  }
}
```

I've tried a few combination of commands and selectors with no success.

**Comment by davesnx** [comment]
This error is from jq: `ingress/0 is not defined at <top-level>`.

I'm afraid that you have an issue with jq itself. loadBalancer looks empty and you want to check if any of the childs exists. I have it working like that:

`→ jq_ '.body.status.loadBalancer | .ingress[]?.ip' data.json`
