### ISSUE TITLE
travis-deploy-once is listed as a dependency instead of devDependency

### ISSUE THREAD

**Issue by brocoli** [sanack/node-jq#129]
Please switch the travis-deploy-once dependency into a devDependency.

This package depends on @babe/core and a number of other dependencies, bloating considerably the builds of any package that depends on node-jq.

**Comment by davesnx** [comment]
Hey @brocoli, I suggest to install all your dependencies with `--prod`. It will not install the devDependencies of each pacakge.

Thanks for reporting the issue
