### ISSUE TITLE
Add a bin declaration in package.json

### ISSUE THREAD

**Issue by stefaneg** [sanack/node-jq#142]
Would be nice to also have a link to jq in node_modules/.bin

**Comment by davesnx** [comment]
Hey @stefaneg 

Do you mean, adding a bin property inside package.json that points into the binary?

```json
"bin": "node_modules/.bin/jq"
```

https://docs.npmjs.com/files/package.json#bin

I will create a PR adding it if it's the case.
Thanks for reporting it!
