### ISSUE TITLE
Can't install on windows

### ISSUE THREAD

**Issue by IAMtheIAM** [sanack/node-jq#146]
```
win_delay_load_hook.cc
error C2039: 'SetAccessCheckCallbacks': is not a member of 'v8::ObjectTemplate'
```

Node 10.13.0
Same happens with 8.11.3

I installed `windows-build-tools` so what is this package expecting?

**Comment by davesnx** [comment]
HEY @IAMtheIAM 

I will try to add Node 10 in https://ci.appveyor.com/project/sanack/node-jq
and try to reproduce it there.

Do you have any idea, what's the error message telling?

**Comment by IAMtheIAM** [comment]
Unfortunately I do not know what it means, were you able to get any insight into this?

**Comment by davesnx** [comment]
I used Windows 10 in our CI and didn't had any problem. I will close this issue and re-opened if there's more info about this issue.

https://github.com/sanack/node-jq/pull/153
