### ISSUE TITLE
spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by dwntwnbrown** [sanack/node-jq#149]
The following error is throw [spawn ENAMETOOLONG] when executing the following call on windows (10 and 2012 r2 server) not an issue when running on mac.

    let filter = ".datasets.dbFileReg.versions[]";
    let options = { input: "json", output: "json" };
    let fileProcessingStats = await jq.run(filter, stats, options)
      .then((output) => {
        return output;
      });

"node-jq": "^1.3.1"
npm: 6.4.1
node: v11.3.0

Any insight on resolution would be greatly appreciated.

Additional output from windows 10

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\dbrown\projects\hctra\portal\node_modules\node-jq\bin\jq ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

**Comment by davesnx** [comment]
Hey @dwntwnbrown 

Happens the same with a small json?

**Comment by davesnx** [comment]
I would try input file and try to stress test the call.

If you could send a reproducible case, I would take a look at it myself.

**Comment by davesnx** [comment]
Closing since there's no response for a while. Feel free to open again and I will try to help.

**Comment by bosskay972** [comment]
I have the same problem and it doesn't work with big json but with small json it work perfectly how to fix that ?
here is my error code:

```
(node:15440) UnhandledPromiseRejectionWarning: Error: spawn ENAMETOOLONG
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at Object.spawn (child_process.js:538:9)
    at C:\Users\adela\node_modules\node-jq\lib\exec.js:24:43
    at new Promise (<anonymous>)
    at exec (C:\Users\adela\node_modules\node-jq\lib\exec.js:20:10)
    at C:\Users\adela\node_modules\node-jq\lib\jq.js:24:24
    at new Promise (<anonymous>)
    at Object.run (C:\Users\adela\node_modules\node-jq\lib\jq.js:19:10)
    at C:\Users\adela\node_code\calcDamage1forAll.js:760:28
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mackermans** [comment]
Hi @bosskay972, could you please provide some more information? 

- Did this error occur on the latest node-jq version? (we recently fixed #194, which should allow for bigger json inputs that are not loaded from files)
- What node, npm/yarn and node-jq versions are you using?
- How are you running node-jq? (what does the source code look like?)
- Could you provide steps to reproduce the error, so we can investigate ourselves?

**Comment by bosskay972** [comment]
I don't want to copy paste because it's an heavy topic, so i will link you my question I posted on stackoverflow: here is the [link](https://stackoverflow.com/questions/57166113/how-to-fix-error-spawn-enametoolong-probably-cause-by-jq-in-javascript)

You can check the post, the answer and the comment below the answer and then the chat too there is many information I add frequently if I discover something new.

**Comment by bosskay972** [comment]
Finally I fixed the problem ! I update my version of node_jq in the right folder !

**Comment by mackermans** [comment]
Glad to hear @bosskay972!
