### ISSUE TITLE
Bug: jq not moved to node_modules/.bin

### ISSUE THREAD

**Issue by zaygraveyard** [sanack/node-jq#167]
## Description

After an install of this module, the binary is downloaded and placed in `node_modules/node-jq/bin/jq` but not moved to `node_modules/.bin`

### Test

```bash
mkdir /tmp/node-jq-issue-167
cd /tmp/node-jq-issue-167
npm init -y
npm install node-jq
ls node_modules/node-jq/bin/jq
ls node_modules/.bin/jq
```

## Environment

nodejs version: Node.js v11.15.0 (linux 5.0.13-arch1-1-ARCH)
npm version: 6.9.0
node-jq version: 1.8.1

**Comment by davesnx** [comment]
Hey @zaygraveyard 

That's not a bug, it's an intended behaviour. This package don't provide a binary to execute, just wraps the jq binary. 

As discussed: [here](https://github.com/sanack/node-jq/issues/161), [here](https://github.com/sanack/node-jq/issues/142) and [here](https://github.com/sanack/node-jq/pull/143)

If there's a need to use a package to install the binary of jq, I would create a separate package that only does that.

Thanks for reporting the issue.
