### ISSUE TITLE
Release 1.9.0 isn't built

### ISSUE THREAD

**Issue by lostinplace** [sanack/node-jq#170]
Just what I said in the intro, the release in github isn't actually built.  As a workaround, you can use the release in my fork:

https://github.com/lostinplace/node-jq/releases/download/v1.9.0/node-jq@1.9.0.tar.gz

**Comment by davesnx** [comment]
Hey, 

Thanks for pointing that out. I didn't release the build version since I thought that anyone would be interested. Cool that you are!

Aside from that, how did you manage to push a folder to "releases" that is ignored with `.gitignore`?

**Comment by lostinplace** [comment]
I'm going to be real honest, I'm not sure

**Comment by davesnx** [comment]
I will assume that isn't possible. But still, It's a weird use-case. I will close that issue.

Thanks for reporting!
