### ISSUE TITLE
Use JQ to write to JSON

### ISSUE THREAD

**Issue by MartinMuzatko** [sanack/node-jq#192]
## Description

Hello! I'd like to use jq as an alternative to `deep-get-set` or similar to use the same syntax for reading to also write to a file or JSON string/object.

## Relevant Links

We are using hjson to read hjson files. In order to write back specific information for command line use, we created our own hjsonw package that sets the jq-like property:

https://github.com/MartinMuzatko/hjson-config/blob/master/config.js#L96

## Environment

OS: Linux (Alpine, Debian), Windows
linux 4.4.0-17763-Microsoft 

Node.js v12.2.0 
npm 6.9.0

node-jq version:
```bash
1.9.1
```
## Expected limitations

Since jq also allows writing maps/filters etc, it would be not as trivial to write a setter for the incoming JSON.
I'd already be happy to have an incomplete JQ implementation for writing, to write to arrays and objects. Whereas with existing libs (deep-get-set) I'm having trouble to do so.

**Comment by davesnx** [comment]
Hey @MartinMuzatko 

Seems like a very interesting problem. I might try to help, could you give a little bit more of detail?

What's exactly your trying to do? I understand so far, you receive `field` and `value` where field is jq-like, something: ".pokemon.water". You would like to use jq directly. 

jq can work without a json file, using `--null-input`, like: `jq -n '{"ref": [100, 1]} | .ref'`.

But I don't exactly see where node-jq plays with this, you can rewrite setProperty with `jq -n` and assigning value.


```js
    async setProperty(field, value) {
        if (!field) return false;
        // Since JQ only allows setting specific properties via e.g. .Host.Name,
        // We should also support this here and trim it for use with deep-get-set.
        // TODO: implement node implementation of JQ: https://www.npmjs.com/package/node-jq
        field = field.indexOf('.') == 0 ? field.substring(1) : field;
        let config = await this.get();
        deep(config, field, value);
        this.set(config);
    }
```

I didn't try it, but managing the `field` argument and the value to work something like that: `$ jq  -n '{"ref": { "max": 100, "min": 50 }} | .ref.max = 2'` should do the job.

Let me know if I miss understood wrongly and you might need some change on node-jq itself.

Thanks for the detailed issue!

**Comment by MartinMuzatko** [comment]
Hello @davesnx 
This is exactly what I need, now just from within nodejs programmatically if possible.

I will test if I can do this purely with jq -n.
Thanks!
