### ISSUE TITLE
Global installation not working with nvm

### ISSUE THREAD

**Issue by stefaneg** [sanack/node-jq#227]
MacOS Mojave, nvm 0.33.6

Reproducing:

nvm use v12.13.0
npm i node-jq -g

ls -l ~/.nvm/versions/node/v12.13.0/bin | grep jq

I would expect jq to be installed here. Since there is no bin entry in node-jq/package.json, npm will not do it. So it seems like the install-binary script is not working properly under nvm.

**Comment by davesnx** [comment]
Hello @stefaneg,
Thanks for opening a new issue.

`install-binary` adds the jq binary under it's own node_modules and inside `bin/`. So, when you install node-jq as a global, it woudn't be on the binary folder that nvm neither your local env expects to live the jq.

The current behaviour It's an issue that we mitigate moving the jq binary in `bin/`.

Here are some links for reference about the issues that I mention:

https://github.com/sanack/node-jq/issues/161
https://github.com/sanack/node-jq/issues/167
https://github.com/sanack/node-jq/issues/171

Thanks!

**Comment by stefaneg** [comment]
Seems to me that the cheap solution here is to improve documentation to state that node-jq is a wrapper around a binary, and point out that the proper way for global install is to use native package managers such as brew or apt to install jq.

I would also look into hooking into earlier lifecycle events to run the script, which might allow npm to create the symlink based on a bin entry in package.json. It is probably too late to have the binary installed during postinstall.

**Comment by davesnx** [comment]
I will try to do that, either the documentation or change the hook 👍

**Comment by silverkorn** [comment]
Isn't the npm install switch `--no-bin-links` for avoiding these kind of issue?
I would personally have done something like the following to detect if it's already installed:
```javascript
var jqPath = require('os').platform() === 'win32' ? require('child_process').spawnSync('where', ['jq']).stdout.toString() : require('child_process').spawnSync('which', ['jq']).stdout.toString();
```
---
Otherwise, my workaround (To do once on every new instance):
```bash
# Bash / Sh
export PATH=$PATH:"$(dirname $(which node))/node_modules/node-jq/bin" 
```
```batch
:: Batch
FOR /F "tokens=* USEBACKQ" %a IN (`where node 2^> NUL`) DO SET PATH=%PATH%;%~da%~panode_modules\node-jq\bin
```

**Comment by davesnx** [comment]
You can always skip the installation globally with `$ export NODE_JQ_SKIP_INSTALL_BINARY=true`

**Comment by silverkorn** [comment]
Automation of detection is marvelous, that's why I suggested the "jqPath" detection part as the default installation behavior (as the hook).
I tend to install applications/tools that becomes available directly in my terminal by default after an `nvm install -g`, such as `angular-cli`, `yarn`, etc. So at first I thought I could do the same with this project.
