### ISSUE TITLE
how to get json output?

### ISSUE THREAD

**Issue by bties-ogawa** [sanack/node-jq#230]
Hi, thanks nice module. i like it.
but help me.

### Description

I want to get json type response.
but it was string.

like as below:
"aaaa"\n
"bbbb"\n
"cccc"\n

can i get json?

* i hope strings is not quoted by '-r' option.

### Test Source

```js
  const filter = '.results[].title';
  const opt = {
    input: 'json',
    output: 'json'
  };

  jq.run(filter, res, opt).then( out => {
    console.log(typeof out);
  } ).catch( err => {
    console.log(err);
  });
```

### Error Message & Stack Trace

```
string
```

## Environment

- Windows 10 Professional
- `npm i node-jq --save`
- `/node_modules/node-jq/jq.exe` was installed

**Comment by davesnx** [comment]
Hey @bties-ogawa 

That's the current behaviour with jq:

```bash
q -r '.results[]' <<<'
 {"results": ["SEA-739", "SEA-2", "AWS-2", "OLA"]}'
```

```bash
SEA-739
SEA-2
AWS-2
OLA
```

There's no way to currently parse the output when it's a query like `[]`.
When output is json we try to parse and if isn't possible we return the output as it is.

Some times you could change the output of the query inside the query, something like: `reduce .[] as $i ({}; .[$i.name] = $i)` and create an object of an array, you could try a workaround like that.

Hope it helped.
