### ISSUE TITLE
Passing Variables to jq.run

### ISSUE THREAD

**Issue by shyamvala** [sanack/node-jq#244]
## Description

I am curious if there is a way to pass variables from the JS code to the jq.run command. 

For example in JQ, you could do something like this, here `dt` is the variable that is being passed.
`cat sample.json | jq --arg dt "2017-01-01" '{first_name, last_name, $dt}'`

I tried to pass some arguments to jq.run method in the options object but got a validation error, looking at the source or tests doesnt show a way to send such variables, was curious if there was something that supports this behaviour.

Cheers!

**Comment by davesnx** [comment]
Hey @shyamvala 

Right now, the only way do that is to use string concatenation, or for simplicity, template strings. https://developers.google.com/web/updates/2015/01/ES6-Template-Strings

We could create a "variables" key inside the parameters, doesn't seem much needed tho.

WDYT?

Thanks for opening an issue

**Comment by davesnx** [comment]
Closing, since the problem seems solved.
