### ISSUE TITLE
Streaming input

### ISSUE THREAD

**Issue by christianbundy** [sanack/node-jq#292]
## Description

Is it possible to run JQ on a stream? I'm integrating node-jq with a popular streaming library but having to run `jq.run` for each  item in the source.

## Relevant Links

- https://github.com/christianbundy/pull-jq

**Comment by davesnx** [comment]
Hey @christianbundy, it's possible but I never had to. I'm pointing to [here](https://github.com/sanack/node-jq/issues/205) since seem the same problem. Closing this.

Thanks for opening an issue.
