### ISSUE TITLE
IOptions type is missing "input"

### ISSUE THREAD

**Issue by danfarewell** [sanack/node-jq#299]
## Error
IOptions type is missing attribute "input" and therefor it can't be specified without errors. Workaround for now is to cast it as any. The fix should be pretty easy by simply adding input to the IOptions interface and adding the allowed types as "json", "file" or similar.

## Environment
node v13.11.0
npmv 6.13.7

**Comment by davesnx** [comment]
Fixed https://github.com/sanack/node-jq/pull/301
