### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by jfoclpf** [sanack/node-jq#306]
```
joao@toshiba:~/autocosts$ npm i node-jq -D

> node-jq@1.11.1 postinstall /home/joao/autocosts/node_modules/node-jq
> npm run install-binary


> node-jq@1.11.1 install-binary /home/joao/autocosts/node_modules/node-jq
> node scripts/install-binary.js

Building jq from https://github.com/stedolan/jq/releases/download//jq-1.6/jq-1.6.tar.gz
Error: Command failed: /bin/sh -c autoreconf -fi
/bin/sh: 1: autoreconf: not found


    at /home/joao/autocosts/node_modules/bin-build/node_modules/execa/index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0) {
  code: 127,
  killed: false,
  stdout: '',
  stderr: '/bin/sh: 1: autoreconf: not found\n',
  failed: true,
  signal: null,
  cmd: '/bin/sh -c autoreconf -fi',
  timedOut: false
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-jq@1.11.1 install-binary: `node scripts/install-binary.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-jq@1.11.1 install-binary script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joao/.npm/_logs/2020-06-01T16_24_23_777Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-jq@1.11.1 postinstall: `npm run install-binary`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-jq@1.11.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joao/.npm/_logs/2020-06-01T16_24_24_428Z-debug.log
```

```
node -v
v12.17.0
joao@toshiba:~/autocosts$ npm -v
6.14.5
joao@toshiba:~/autocosts$ yarn -v

```

**Comment by ryoju-ohata** [comment]
Try again after the following command.

```
$ sudo apt install libtool
```

**Comment by ryoju-ohata** [comment]
> ```
> joao@toshiba:~/autocosts$ npm i node-jq -D
> 
> > node-jq@1.11.1 postinstall /home/joao/autocosts/node_modules/node-jq
> > npm run install-binary
> 
> 
> > node-jq@1.11.1 install-binary /home/joao/autocosts/node_modules/node-jq
> > node scripts/install-binary.js
> 
> Building jq from https://github.com/stedolan/jq/releases/download//jq-1.6/jq-1.6.tar.gz
> Error: Command failed: /bin/sh -c autoreconf -fi
> /bin/sh: 1: autoreconf: not found
> 
> 
>     at /home/joao/autocosts/node_modules/bin-build/node_modules/execa/index.js:231:11
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async Promise.all (index 0) {
>   code: 127,
>   killed: false,
>   stdout: '',
>   stderr: '/bin/sh: 1: autoreconf: not found\n',
>   failed: true,
>   signal: null,
>   cmd: '/bin/sh -c autoreconf -fi',
>   timedOut: false
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-jq@1.11.1 install-binary: `node scripts/install-binary.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-jq@1.11.1 install-binary script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/joao/.npm/_logs/2020-06-01T16_24_23_777Z-debug.log
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-jq@1.11.1 postinstall: `npm run install-binary`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-jq@1.11.1 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/joao/.npm/_logs/2020-06-01T16_24_24_428Z-debug.log
> ```
> 
> ```
> node -v
> v12.17.0
> joao@toshiba:~/autocosts$ npm -v
> 6.14.5
> joao@toshiba:~/autocosts$ yarn -v
> ```

Try again after the following command.

```
$ sudo apt install libtool
```

**Comment by jfoclpf** [comment]
Thank you @ryoju-ohata 
But in my POV, npm packages should not depend on third-parties not available at npm itself, nor oblige the user to do sudo.

**Comment by davesnx** [comment]
Hey @ryoju-ohata and @jfoclpf 

Sorry for not responding earlier. node-jq relies on jq and tries to do the best to install it for you, so in fact this package relies on "third-parties", since needs to build jq depending on your architecture. I would disagree on `packages should not depend on third-parties not available at npm itself` then.

This is why we added the possibility to SKIP_INSTLATION and make sure you have an option to still install jq (or have it already in your system) and use node-jq.

Thanks for @ryoju-ohata for solving the issue and Thanks @jfoclpf for opening it.

**Comment by jfoclpf** [comment]
@davesnx thanks, I indeed agree with you on that (that the program must not be in npm it selft), though I fully disagree that one should be obliged to do some `sudo` command.
Anyway thanks
