### ISSUE TITLE
Can't exec "aclocal": No such file or directory

### ISSUE THREAD

**Issue by saiichihashimoto** [sanack/node-jq#349]
We have a [Vercel](http://vercel.com/) and [Next.js](https://nextjs.org/) stack. In local development, having `node-jq` in `devDependencies` works great! However, since most CIs install the dev dependencies as well for building, this will attempt building the jq binary which results in the following error:

![image](https://user-images.githubusercontent.com/2819256/101683789-0d88b580-3a2b-11eb-962a-cd791d530c92.png)

```
14:22:44.194 | > node-jq@1.11.3 postinstall /vercel/workpath0/node_modules/node-jq
14:22:44.194 | > npm run install-binary
14:22:44.423 | > node-jq@1.11.3 install-binary /vercel/workpath0/node_modules/node-jq
14:22:44.423 | > node scripts/install-binary.js
14:22:44.579 | Building jq from https://github.com/stedolan/jq/releases/download//jq-1.6/jq-1.6.tar.gz
14:22:46.941 | Error: Command failed: /bin/sh -c autoreconf -fi
14:22:46.942 | Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
14:22:46.942 | autoreconf: failed to run aclocal: No such file or directory
14:22:46.942 | at /vercel/workpath0/node_modules/execa/index.js:231:11
14:22:46.942 | at runMicrotasks (<anonymous>)
14:22:46.942 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
14:22:46.942 | at async Promise.all (index 0) {
14:22:46.942 | code: 1,
14:22:46.942 | killed: false,
14:22:46.942 | stdout: '',
14:22:46.942 | stderr: `Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.\n` +
14:22:46.942 | 'autoreconf: failed to run aclocal: No such file or directory\n',
14:22:46.942 | failed: true,
14:22:46.942 | signal: null,
14:22:46.942 | cmd: '/bin/sh -c autoreconf -fi',
14:22:46.942 | timedOut: false
14:22:46.942 | }
14:22:46.948 | npm ERR! code ELIFECYCLE
14:22:46.948 | npm ERR! errno 1
14:22:46.951 | npm ERR! node-jq@1.11.3 install-binary: `node scripts/install-binary.js`
14:22:46.951 | npm ERR! Exit status 1
14:22:46.951 | npm ERR!
14:22:46.951 | npm ERR! Failed at the node-jq@1.11.3 install-binary script.
14:22:46.951 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I'm not sure how to resolve this. It seems excessive to somehow install `aclocal` on these build machines, so I'm hoping there's a simpler solution. Is there a way to have `node-jq`'s deployment process build the binary as part of it's release?

**Comment by davesnx** [comment]
Hey @saiichihashimoto 

Building the binaries on each release might solve this issue but will generate a bunch of other problems regarding different archs. 

We provide a way to skip the binary installation (since most CIs have already jq installed) with a env variable: `export NODE_JQ_SKIP_INSTALL_BINARY=true`.

Would this work for your case?

**Comment by saiichihashimoto** [comment]
I think it does! I just set that env var in the CI environments and it seemed to solve the issue. Thanks!
