### ISSUE TITLE
Possible ./node-jq/bin/jq permission issue

### ISSUE THREAD

**Issue by pcorless** [sanack/node-jq#367]
I've been having trouble with a build/bundling because of the permission on  ./node-jq/bin/jq set via fs.constants.S_IXUSR via the install-binary.js .  As result the jq binary only has execute permission and I can't copy bundle etc.  

Any chance there is a small bug with the install-binary.js ?  Wondering if the intent was 

`fs.chmodSync(distPath, fs.constants.S_IXUSR | 0o100)`

instead of 

`fs.chmodSync(distPath, fs.constants.S_IXUSR || 0o100)`

At any rate it would be be great if the executable also had read access.

**Comment by davesnx** [comment]
Hey @pcorless 

I believe it's intended as it is right now. Can I ask, what's the reason to have read access on the binary? 

Thanks for opening the issue!

**Comment by pcorless** [comment]
It's mainly for a build system I'm working with,  lots of copying around and bundling of files.  
I think right now I'm leaning towards using the JQ_PATH and avoid the binary install.  Thanks for the info!
