### ISSUE TITLE
Support CLI calls

### ISSUE THREAD

**Issue by NullDivision** [sanack/node-jq#39]
Currently there is no binary exposed for terminal access and therefor the only option is creating a script to run it. Seems inefficient considering that you could simply have:

```
{
    "scripts": {
        "build:json": "jq -s . *.json > output.json"
    }
}
```

**Comment by davesnx** [comment]
You want the same interface as jq @NullDivision
I don't really get it, you could simple run jq as a binary.

**Comment by NullDivision** [comment]
Node-jq is kind of redundant as jq is basically emulating on a CLI what JS already does natively (ie. handle run Javascript Object Notation). The whole reason one would want jq as a node package is to run it as part of an NPM script.

And while you can run it using a system binary, the person downloading it might not have JQ already installed, hence why it needs to be included as a node module.

**Comment by davesnx** [comment]
> The whole reason one would want jq as a node package is to run it as part of an NPM script.

That's not true, You can run whatever binary through npm scripts, It's exactly what you said.
But could be usefull for rare use cases like mine, that I need to run jq as a javascript process for my atom plugin: [atom-jq](https://github.com/sanack/atom-jq), and I can think some use cases that could be usefull.

>And while you can run it using a system binary, the person downloading it might not have JQ already installed, hence why it needs to be included as a node module.

Basically there's a [prerequirement](https://github.com/sanack/node-jq#prerequisites) that forces the system to have jq installed. 

I don't see your point of "**Support CLI calls**".

**Comment by NullDivision** [comment]
I see. Then it's kind of a moot point. `jq-cli-wrapper` does include builds.

Thanks for the attention either way. :)

**Comment by davesnx** [comment]
We gonna implement some kind of this in the near future @NullDivision

**Comment by davesnx** [comment]
@NullDivision, I actually implement something to make this happen https://github.com/sanack/node-jq/pull/41
