### ISSUE TITLE
[Feature Request] Filter formatting

### ISSUE THREAD

**Issue by fjcaetano** [sanack/node-jq#392]
## Description

The filter applied should be formattable for readability and reduced complexity.

### The Problem
I'm using the following filter to extract and map the data I need into a single level array:
```js
jq.run(
  '[.data.matchdays[].groups[].matches[] | { id, kickoff, score_home, score_away, period, home_team: .team_home.name, away_team: .team_away.name, competition: .competition.name } ]',
  data,
)
```

### The Solution

That filter is already quite long, but not even close to some complex filters and mappings that could be applied to `jq`, however this would be much easier to read if it could be written as:
````js
jq.run(
  ```
  [
    .data
    .matchdays[]
    .groups[]
    .matches[] | {
      id,
      kickoff, 
      score_home,
      score_away,
      period,
      home_team: .team_home.name,
      away_team: .team_away.name,
      competition: .competition.name
    }
  ]
  ```,
  data,
)
````

Unfortunately, the lib does not accept this. I suppose it's forwarding the raw string to the `jq` process, right? Maybe it could have some pre-processing?

### How to tackle it
This might be as simple as deleting `\n` and `\t` from the filter, but there might be some edge cases that I'm not foreseeing here.

**Comment by davesnx** [comment]
Hey @fjcaetano 

For now, `node-jq` doesn't support any transformation on the input and it is unlikely that it will support it. For various reasons, but the most important is that would introduce a lot of bugs or even breaking apps. Another reason is that pre-processing the string it might make sense for your use-case but it's hard to get it right for all use-cases.

I would recommend try to solve readability in your code, such as:

```javascript
const filter = [
  ".data",
  ".matchdays[]",
  ".groups[]",
  ".matches[]",
  "| {",
    "id,",
    "kickoff,",
    "score_home,",
    "score_away,",
    "period,",
    "home_team: .team_home.name,",
    "away_team: .team_away.name,",
    "competition: .competition.name",
  "}",
].join("");
```

This introduces a little bit of transformation but is similar to what you suggest as pre-processing.

Thanks for opening the issue, hope it helps.
