### ISSUE TITLE
Would it be possible for you to update dependencies?

### ISSUE THREAD

**Issue by synedra** [sanack/node-jq#398]
## Prerequisites

- We ask only that you do your best to provide as much information as possible so we can better help you.
- Ensure the issue isn't already reported.
- Ensure the issue isn't about jq itself.
- Should be reproducible with the latest node-jq version.

*Delete the above section and the instructions in the sections below before submitting*

## Description

When I install node-jq there are a lot of deprecated/moved module warnings.  This makes my package look shaky.  Could you get rid of the hapi stuff and other deprecated things?

### Test Source

```js
// Avoid posting hundreds of lines of source code.
// Edit to just the relevant portions.
```

### Error Message & Stack Trace

```
COPY THE ERROR MESSAGE, INCLUDING STACK TRACE HERE
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm/yarn, and node-jq.

Run the following to get it quickly:
nodejs version:
```bash
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
```
yarn version:
```bash
yarn --version
```
npm version:
```bash
npm --version
```
node-jq version:
```bash
cat node_modules/node-jq/package.json | grep "version"
```

**Comment by davesnx** [comment]
Hey @synedra 

I keep merging PRs from dependabot so most dependencies should be up to date. Aside from hapi, can you share which dependencies you want to see them updated?

**Comment by davesnx** [comment]
Hey @synedra, If you are interested in making your package look less shaky, I encourage you to create a PR with your desired changes. For now I don't have the bandwidth to fix those
