### ISSUE TITLE
Create binary wrapper

### ISSUE THREAD

**Issue by mackermans** [sanack/node-jq#40]
Download the `jq` executable automatically when installing this package, or include it in the source code. Reference it local instead of global. This removes the requirement of having installed  `jq` already.

Maybe in combination with [this](https://github.com/kevva/bin-wrapper) package.

**Comment by davesnx** [comment]
The bin-wrapper seems the correct to wrapp the binary, I see issues doing the script of downloading the jq and building it.

**Comment by mackermans** [comment]
Implemented in #41
