### ISSUE TITLE
Can't be used in a Electron app due to node_modules/joi/lib/ref.js:80

### ISSUE THREAD

**Issue by DaniellMesquita** [sanack/node-jq#425]
Is Joi related to Hapi (https://github.com/sanack/node-jq/issues/410)?

Node version: v14.17.3

> App threw an error during load
> /media/daniell/c229ba9f-c21a-4d8e-afcd-01bf8b9847d0/1/Floflis/apps/flofliscentral/node_modules/joi/lib/ref.js:80
>     return exports.create(key, { ...options, in: true });
>                                  ^^^
> 
> SyntaxError: Unexpected token ...
>     at createScript (vm.js:74:10)
>     at Object.runInThisContext (vm.js:116:10)
>     at Module._compile (module.js:533:28)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/media/daniell/c229ba9f-c21a-4d8e-afcd-01bf8b9847d0/1/Floflis/apps/flofliscentral/node_modules/joi/lib/compile.js:6:13)
> A JavaScript error occurred in the main process
> Uncaught Exception:
> /media/daniell/c229ba9f-c21a-4d8e-afcd-01bf8b9847d0/1/Floflis/apps/flofliscentral/node_modules/joi/lib/ref.js:80
>     return exports.create(key, { ...options, in: true });
>                                  ^^^
> 
> SyntaxError: Unexpected token ...
>     at createScript (vm.js:74:10)
>     at Object.runInThisContext (vm.js:116:10)
>     at Module._compile (module.js:533:28)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/media/daniell/c229ba9f-c21a-4d8e-afcd-01bf8b9847d0/1/Floflis/apps/flofliscentral/node_modules/joi/lib/compile.js:6:13)
> 

This is after adding "const jq = require('node-jq');" inside main.js.
Before, I added this inside HTML and it compiled, but also threw this error, on Electron Chromium console: "SyntaxError: Unexpected token ..."

@sanack @davesnx

**Comment by davesnx** [comment]
Hey, @DaniellMesquita 

Never tried to run it inside electron, someone did a while ago: https://github.com/wellsjo/JSON-Splora. Could you try v0.5.0 just to discard the Joi?

I will be happy to remove it if it causes issues.

**Comment by DaniellMesquita** [comment]
@davesnx

> Could you try v0.5.0 just to discard the Joi?

Did you mean this: https://github.com/sanack/node-jq/releases/tag/v0.5.0?

Would `npm install node-jq@0.5.0` work?

**Comment by davesnx** [comment]
Exactly @DaniellMesquita

**Comment by DaniellMesquita** [comment]
How to get an JSON value in one line and without using `console.log` as input, but `return`?
Based on [this question](https://stackoverflow.com/questions/69249944/directly-return-stdout-instead-of-logging-on-console#69249944).

**Comment by DaniellMesquita** [comment]
The [username](https://www.npmjs.com/package/username) NPM package enables me to just use `username()` to get a result.

I would like that node-jq could be that simple, by just using something like `jq.run("'.abilities[].moves' /path/to/bulbasaur.json")` in one line and directly returns (instead of `console.log`) the result. Just like the username package does.

**Comment by davesnx** [comment]
Hey @DaniellMesquita 

Your question is more like: "It is possible to run node-jq as asynchronous operation, without using Promises (async)". It's possible to run a command in the terminal and return back the results as a synchronous operation, but node-jq isn't implemented that way.

Can you explain why do you need it? Maybe the solution is somewhere else.

I'm closing this since I would assume that your initial issue got resolved. I will keep an eye on Joi since it has raised a few issues in the past, Thanks for opening the issue!

**Comment by DaniellMesquita** [comment]
Sorry for the offtopic. I agree on closing this issue.

Thanks for you helpful suggestion about using an older version (in this case, [v0.5.0](https://github.com/sanack/node-jq/releases/tag/v0.5.0) through `npm install node-jq@0.5.0`).

I will test if it works and may request or not to re-open the issue, if there is a need.

**Comment by DaniellMesquita** [comment]
> @davesnx, The username NPM package enables me to just use username() to get a result.
> 
> I would like that node-jq could be that simple, by just using something like jq.run("'.abilities[].moves' /path/to/bulbasaur.json") (using the same standard as jq in the shell) in one line and directly return (instead of console.log) the result. Just like the username package does.

forked and improved on this issue: https://github.com/sanack/node-jq/issues/430
