### ISSUE TITLE
Run using `npx node-jq`

### ISSUE THREAD

**Issue by lgarron** [sanack/node-jq#427]
If you run `npx node-jq`, you get:

```
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lgarron/.cache/npm/_logs/2021-08-31T08_29_37_859Z-debug.log
```

Would it be easy to support `npx`?

**Comment by davesnx** [comment]
Hey @lgarron, running node-jq with npx doesn't make much sense for the nature of the project. node-jq isn't a CLI, tt's a wrapper on top of jq (which it is in fact, a CLI). Node-jq is used to call jq programmatically from node. 

Could you explain what do you expect to happen in that case? 

I'm closing this

**Comment by lgarron** [comment]
I was looking for a way to invoke `jq` using `npx` because it's much easier to use `npx` for all scripting dependencies than requiring people to install packages like `jq` separately.

The project description sounded general enough to cover that:

> node-jq is a Node.js wrapper for jq - a lightweight and flexible command-line JSON processor

**Comment by davesnx** [comment]
Hey @lgarron 

Better late than never, I released a version of node-jq that supports this, check the issue: https://github.com/sanack/node-jq/issues/614
