### ISSUE TITLE
`jq` executable has the wrong permissions

### ISSUE THREAD

**Issue by carlo-quinonez** [sanack/node-jq#439]
## Description

The `jq` executable has the wrong permissions. I think this has been fixed in the latest commits. Will this fix be released soon?

## Environment

node 12.22.6
npm 7.24
node-jq 2.0.1

**Comment by davesnx** [comment]
Just retriggered the build+publish, for some reason Travis didn't run automatically. Will be published after that.

**Comment by davesnx** [comment]
It was fixed in https://github.com/sanack/node-jq/commit/7935a4e8716398a95731247c01cdc774486c29da but Travis decided to not run. I will migrate to Github Actions so this won't happen.

I'm releasing manually a 2.0.2 version.

**Comment by davesnx** [comment]
Fixed on 2.0.2

Thanks for reporting an issue
