### ISSUE TITLE
cannot open `node_modules/node-jq/bin/jq` for reading: permission denied 

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [sanack/node-jq#440]
I'm unable to deploy a google cloud function that relies on `node-jq`

```
For Cloud Build Stackdriver Logs, visit: https://console.cloud.google.com/logs/viewer?project=xxx.xxx.cloudbuild
............................failed.
ERROR: (gcloud.functions.deploy) OperationError: code=13, message=Build failed: cp: cannot open 'node_modules/node-jq/bin/jq' for reading: Permission denied; Error ID: be8da553
[gcloud] exited with code 1
```

I'm assuming there is some cloud environment security that prevents execution of a local binary.

Related - https://github.com/sanack/node-jq/issues/374

**Comment by davesnx** [comment]
It was fixed in https://github.com/sanack/node-jq/commit/7935a4e8716398a95731247c01cdc774486c29da but Travis decided to not run. I will migrate to Github Actions so this won't happen.

I'm releasing manually a 2.0.2 version. 

Closed related https://github.com/sanack/node-jq/issues/439
