### ISSUE TITLE
[BUG] Version 2.0.0, 2.0.1, 2.0.2 come without lib directory

### ISSUE THREAD

**Issue by InsOpDe** [sanack/node-jq#441]
the latest releases do not come with a prebuild `lib` directory, thus making it impossible to use the library.

the main property of each `package.json` directs to "lib/jq.js" which is not present when creating a new package and installing the package.

reproduction:
```
npm init
npm install node-jq
ls node_modules/node-jq
bin  docs  LICENSE.md  package.json  README.md  scripts  src
```

it can be fixed by installing the `1.12.0` version which includes the prebuild `lib` directory

**Comment by davesnx** [comment]
Release a 2.1.0 version with the lib folder.

There was an issue with our CI running in Travis, moved to Github actions and solved

Thanks for reporting.
