### ISSUE TITLE
Install on Mac OSX fails with CHMOD error

### ISSUE THREAD

**Issue by babignano** [sanack/node-jq#45]
```
npm ERR! Darwin 15.4.0
npm ERR! argv "<path>/.nvm/versions/node/v4.5.0/bin/node" "/Users/babignano/.nvm/versions/node/v4.5.0/bin/npm" "i"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! path <path>/node_modules/node-jq/node_modules/.bin/jq
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '<path>/node_modules/node-jq/node_modules/.bin/jq'
npm ERR! enoent ENOENT: no such file or directory, chmod '<path>/node_modules/node-jq/node_modules/.bin/jq'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!    <path>s/npm-debug.log
```

This might be an issue where on the install script is checking for `node_modules/node-jq/node_modules/.bin/jq` when it should be checking for `node_modules/.bin/jq`

I've attempted this with both `sudo npm install node-jq` and `npm install node-jq`

I'm on npm v3.10.6.

**Comment by davesnx** [comment]
Hey @babignano,
Thanks for create the issue, seems like the script of installing the binary doesn't recognise the parent node_modules and tries to find jq inside their own binary dependencies.

The work arround for now, could be install jq globally. 

I will try to fix this soon.

**Comment by davesnx** [comment]
We have two options to solve that bug, @mackermans:
- Find recursively the parent path and install the binary there.
- Or use [node-gyp](https://github.com/nodejs/node-gyp) to do the binding with C.

**Comment by davesnx** [comment]
Hey @babignano, can you try with the new version@0.3.13 ?

**Comment by babignano** [comment]
@davesnx Thanks Dave, really appreciate the help. 

I'll give it a shot today 👍
