### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by gnhbuchanan** [sanack/node-jq#454]
Every time I try to uninstall this package it reinstalls itself if i open a new terminal window, how do I uninstall?

i have tried multiple combinations 

npm uninstall node-jq

**Comment by davesnx** [comment]
Hey @gnhbuchanan 

Can you share some steps to reproduce? 

Please follow the issue template: https://github.com/sanack/node-jq/blob/main/.github/issue_template.md

**Comment by gnhbuchanan** [comment]
## Description

I installed this package in my top level directory. I am a mac user so I either ran npm i node-jq or sudo npm i node-jq.

Shortly thereafter, I realized that this was not an install that I needed for my project, so I deleted it. 

I tried npm uninstall node-jp with many combinations of sudo, ignore scripts, save flags. 

The package is removed from my node_modules folder, but it looks like this install affected every other module in my node_modules folder. 

If I reboot terminal, or open a new terminal window after uninstalling, this package keeps reinstalling itself. 

Even if I don't uninstall the package and I open a new terminal window, it starts an installation process. 

### Test Source

```js
// Avoid posting many lines of source code that aren't related with the issue.
```

### Error Message & Stack Trace

These are the prompts that show up every time I open a window or reboot terminal. 

```bash
> node-jq@2.1.0 postinstall /Users/username/node_modules/node-jq
> npm run install-binary


> node-jq@2.1.0 install-binary /Users/username/node_modules/node-jq
> node scripts/install-binary.js

Downloading jq from https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
Downloaded in /Users/username/node_modules/node-jq/bin
```

## Environment

I am using node v12.13.1
macOS Catalina Version 10.15.7

**Comment by gnhbuchanan** [comment]
Apologies, this was all a result of my own doing. I am closing the issue, thank you for the follow up and sorry for the inconvenience.
