### ISSUE TITLE
fails to install to node_modules/.bin if jq is not installed on system

### ISSUE THREAD

**Issue by wellsjo** [sanack/node-jq#47]
I am on osx

**Comment by wellsjo** [comment]
it looks like this was fixed

**Comment by mackermans** [comment]
@wellsjo Version `0.3.13` was published to npm but `package.json` wasn't updated, and neither was the corresponding tag pushed to git. I updated it all to version `0.3.14`, could you try that one out and let me know if that fixes it?

**Comment by wellsjo** [comment]
@mackermans installing `0.3.14` works now. However, I still have a problem with the jq installation.

Steps to reproduce:
1. uninstall jq from system
2. in project: `npm i node-jq --save`

After this, there is no `jq` in the `node_modules/.bin` directory. However, `jq` has been installed to `/usr/local/bin/jq`.

I am using this as part of an Electron project.  Since it installs to `/usr/local/`, the Electron builds are failing.

**Comment by davesnx** [comment]
Hey @mackermans and @wellsjo 

Sorry for jumping into this but It's the expected behaviour, if isn't installed globally tries to install on `/usr/local/bin`.

If there's any issue arround that, as a work-arround, you can install jq globally before install `node-jq`

**Comment by wellsjo** [comment]
@davesnx is `node-jq` the wrong tool to use for my Electron app then? I don't see ho installing jq globally first would fix this issue. I need the binary somewhere in the project directory so that Electron can bundle it (at least I think that's how that works).

**Comment by davesnx** [comment]
Not really, we change a little bit the behaviour of installing it global, now we install it local on the module. Next version is near and would be fixed.

**Comment by wellsjo** [comment]
@davesnx awesome, can't wait

**Comment by mackermans** [comment]
@wellsjo Could you try with version `0.4.0`?

**Comment by wellsjo** [comment]
@mackermans 👍  thank you! 😄
