### ISSUE TITLE
Why not install?

### ISSUE THREAD

**Issue by mrak1001** [sanack/node-jq#487]
![image](https://user-images.githubusercontent.com/15646057/153713544-10c88ffc-263d-4646-aebe-837880169090.png)

**Comment by davesnx** [comment]
There's nothing on this issue that I can understand. If there's any problem with the installation, please describe it with words and make a reproduction in a repo/gist. Feel free to re-open it with more information.

Thanks.

**Comment by mortezaataiy** [comment]
try https://github.com/sanack/node-jq#advanced-installation

```
export NODE_JQ_SKIP_INSTALL_BINARY=true
OR
npm install node-jq
npm install node-jq --ignore-scripts
```
@mrak1001
