### ISSUE TITLE
Need the current version updated on NPM

### ISSUE THREAD

**Issue by Symbolic76** [sanack/node-jq#500]
Hello

The current version of the project on Github is up to date and everything is fine.
But currently on NPM, the version still has semantic-release packages in dependencies in `package.json`.
If you could release a version on NPM, where the two packages are moved in devDependencies, it could be very nice.

Thanks.

**Comment by davesnx** [comment]
Published 2.2.0 into npm with latest changes. This should be automatic from now on. I will keep this open until you say works for you.

**Comment by tyler-dunkel** [comment]
we recently started seeing issues in our tool which uses node-jq under the hood. I wonder if it might be due to this latest release. 

Here is the error text we are seeing:
```
'/Users/myUser/.nvm/versions/node/v16.12.0/
    lib/node_modules/@myOrg/myPackage/node_modules/node-jq/lib/jq.js'. Please
    verify that the package.json has a valid "main" entry
    Code: MODULE_NOT_FOUND
```

**Comment by davesnx** [comment]
Hey @tyler-dunkel 

Can you share more information about this?

- Which version are you running? 
- Is this on run-time? install-time?
- Where are you running this code?

**Comment by davesnx** [comment]
I debugged myself and seems like the build artifacts aren't published to npm. I will fix it asap. Thanks for reporting, but please, next time give all the info upfront.

**Comment by davesnx** [comment]
Pushed 2.3.0 with the fix. The "lib" folder wasn't pushed. 

Thanks!
