### ISSUE TITLE
NPM package is missing TypeScript definition files in lib

### ISSUE THREAD

**Issue by donaldoakes** [sanack/node-jq#505]
## Description
Latest node-jq version 2.3.0 on npmjs.com has no *.d.ts files in lib directory, resulting in Typescript compilation errors.

### Test Source

```
npm install --save node-jq
npm run build
```

### Error Message & Stack Trace

```bash
error TS7016: Could not find a declaration file for module 'node-jq'. '/Users/donoakes/workspaces/scorch/scorch/node_modules node-jq/lib/jq.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/node-jq` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-jq';
```

## Environment

```bash
$npm --version
8.5.5
$ node --version
v17.8.0
```

```bash
$ cat node_modules/node-jq/package.json | grep "version"
  "version": "2.3.0"
```

**Comment by davesnx** [comment]
Hey @donaldoakes 

Just pushed a new version 2.3.1 with a fix for this incident. I was messing around with a fix on the build process and break the TS definitions, now are being pushed into lib folder.

Thanks for the issue
