### ISSUE TITLE
lefthook as a dependency 

### ISSUE THREAD

**Issue by jkozak** [sanack/node-jq#506]
## Description

`node-jq` now has a dependency on `@arkweid/lefthook`.

Installation now creates a file in the project root and also a git hook.  This is far, far too intrusive.  My immediate thought was that this was an attempted hack, and I shall have to review the code to convince myself that it's not.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm/yarn, and node-jq.

Run the following to get it quickly:
nodejs version:
```
Node.js v14.17.2
linux 4.19.0-20-cloud-amd64
```

npm version:

```
6.14.13
```

node-jq version:

```
2.3.1
```

**Comment by davesnx** [comment]
Published a fix for it. It's an accidental dependency, sorry for the troubles.

New version https://github.com/sanack/node-jq/releases/tag/v2.3.2

Thanks for reporting!
