### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by MaanooAk** [sanack/node-jq#54]
Error in console

```
Err: Error: ./configure --disable-maintainer-mode --bindir=C:\Users\Akritas\AppData\Roaming\npm\node_modules\node-jq\bin --libdir=C:\Users\Akritas\AppData\Local\Temp\75b42421-6c9d-42ee-9e2e-d386ba04dd5a && make && make install
Command failed: ./configure --disable-maintainer-mode --bindir=C:\Users\Akritas\AppData\Roaming\npm\node_modules\node-jq\bin --libdir=C:\Users\Akritas\AppData\Local\Temp\75b42421-6c9d-42ee-9e2e-d386ba04dd5a
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by davesnx** [comment]
Hello @MaanooAk 

We didn't implement or test `node-jq` based on Windows. But, the error that you are getting is from trying to install the binary.

I will skip that step from Windows archs and would be necesary to have jq installed globally in your sistem.

**Comment by davesnx** [comment]
@MaanooAk we are running with some problems with Windows. Could you actually join the gitter channel and try to contact me? Seems that jq 1.5 isn't working fine on Windows when we run it with Absolute path... and sincerely I don't have any experience arround Windows.

**Comment by MaanooAk** [comment]
@davesnx I will do some investigating (when I got some time) and I will get back to you

**Comment by davesnx** [comment]
Could you try now with the new release v0.5.0? @MaanooAk

**Comment by MaanooAk** [comment]
Install ok

![capture](https://cloud.githubusercontent.com/assets/6997990/21544163/75fcab10-cdd5-11e6-9f75-eab7aa54ed4f.PNG)

Simple test ok

![capture](https://cloud.githubusercontent.com/assets/6997990/21544177/90d49682-cdd5-11e6-8193-a5b972e8f9d5.PNG)

Other test ??

![capture](https://cloud.githubusercontent.com/assets/6997990/21544189/a74c0300-cdd5-11e6-96b6-473adb2fc2d2.PNG)

Am I doing something wrong?

**Comment by davesnx** [comment]
That potencially fix [JSON-Splora](https://github.com/wellsjo/JSON-Splora) on Windows?

**Comment by MaanooAk** [comment]
It should after some changes in order to prevent the long arguments bugs of `jq`.
I'll take look

**Comment by MaanooAk** [comment]
I fixed it, now it works fine!

**Comment by davesnx** [comment]
Nice @MaanooAk !
