### ISSUE TITLE
[Security] Vulnable library brought in -> decompress-tar@4.1.1

### ISSUE THREAD

**Issue by mlawrence999** [sanack/node-jq#569]
Seems the latest version of node-jq (2.3.5) ends up bringing in the vulnerable library decompress-tar@4.1.1. More details about this vulnerability here - https://security.snyk.io/package/npm/decompress-tar 

The complete dependency tree is:

dependencies:
node-jq 2.3.5
└─┬ bin-build 3.0.0
  ├─┬ decompress 4.2.1
  │ ├── decompress-tar 4.1.1
  │ ├─┬ decompress-tarbz2 4.1.1
  │ │ └── decompress-tar 4.1.1
  │ └─┬ decompress-targz 4.1.1
  │   └── decompress-tar 4.1.1
  └─┬ download 6.2.5
    └─┬ decompress 4.2.1
      ├── decompress-tar 4.1.1
      ├─┬ decompress-tarbz2 4.1.1
      │ └── decompress-tar 4.1.1
      └─┬ decompress-targz 4.1.1
        └── decompress-tar 4.1.1

Please consider changing the dependency tree so decompress-tar@4.1.1 is not used

**Comment by dmtrs** [comment]
Is anyone looking into the issue?

**Comment by kitschpatrol** [comment]
Was able to work around this for the time being:

`package.json`:
```json
  "overrides": {
    "node-jq": {
      "bin-build": "github:brave/bin-build#modernize"
    }
  }
```

**Comment by davesnx** [comment]
Hey @kitschpatrol 

Would you like to push a PR with bin-build vendored with the security fixes patched?
