### ISSUE TITLE
does it work with lambda functions?

### ISSUE THREAD

**Issue by AllanOricil** [sanack/node-jq#587]
does it work with lambda functions?

**Comment by AllanOricil** [comment]
It works, but I have to create a lambda layer with the jq bin in it :/

**Comment by scottsandersdev** [comment]
@AllanOricil Do you have any tips on how to do this? I'm attempting to run this in an aws lambda and exploring it now. Did you just install node-jq in a layer, or did you install jq itself in a layer?

**Comment by AllanOricil** [comment]
I actually did not have time to test it because I was fired 😅
But my research showed it was possible. You can do it this way:

- create a layer and add the bin in its root
- add the layer path to PATH
- use ur preferable runtime to run a shell command

**Comment by scottsandersdev** [comment]
I'm not sure what you mean by "add the layer path to PATH" Is there a PATH variable in aws lambda?

**Comment by AllanOricil** [comment]
> I'm not sure what you mean by "add the layer path to PATH" Is there a PATH variable in aws lambda?

Yes, there is
https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html
