### ISSUE TITLE
package version 4.0.0 not avaliable

### ISSUE THREAD

**Issue by guillermosantana** [sanack/node-jq#610]
This package doesn't exists https://www.npmjs.com/package/node-jq/v/4.0.0 I had to use the version from the release repo 3.0.0 since I got the error:

`code: 'MODULE_NOT_FOUND',
  path: '/home/circleci/project/node_modules/node-jq/package.json',
  requestPath: 'node-jq'
}`

**Comment by davesnx** [comment]
I'm able to install 4.0.0 and running `npm view node-jq` I got the correct info:
```
node-jq@4.0.0 | MIT | deps: 6 | versions: 74
Run jq in node
https://github.com/sanack/node-jq#readme

keywords: jq, json

dist
.tarball: https://registry.npmjs.org/node-jq/-/node-jq-4.0.0.tgz
.shasum: fe7e64966ba168fefd594dd07f490ec6e0c93c35
.integrity: sha512-4vDbxNu+7jSOCVdxkV5E5uwv+nntvLaDr8Ltkk8lZs8d0loRVXS4QZTtmC8gH3GCMMmorr/le6D/wZ2quKmuRg==
.unpackedSize: 1.1 MB

dependencies:
bin-build: ^3.0.0              node-downloader-helper: ^2.1.6
is-valid-path: ^0.1.1          strip-final-newline: ^2.0.0
joi: ^17.4.0                   tempfile: ^3.0.0

maintainers:
- mackermans-admin <maarten.ackermans@gmail.com>
- davesnx <dsnxmoreno@gmail.com>

dist-tags:
latest: 4.0.0

published 3 hours ago by davesnx <dsnxmoreno@gmail.com>
```

Can you give more information about what your setup looks like? Any chance you could push a repro?

**Comment by guillermosantana** [comment]
We run a container that purge the cache from Cloudflare using:

`npm install \
    cloudflare \
    node-jq \
    dotenv \
    psl`

After the job was executed we got the error posted above ^ When looking at the repo releases found that latest version was 3.0.0 and not 4.0.0 therefore I had to change the install to:

`npm install \
    cloudflare \
    node-jq@3.0.0 \
    dotenv \
    psl`

**Comment by davesnx** [comment]
Alright, can you try to run `npm view node-jq` from inside the container? 

As you can see, the file exists: https://www.npmjs.com/package/node-jq/v/4.0.0?activeTab=code

**Comment by davesnx** [comment]
Feel free to re-open in case you see it again. Thanks.
