### ISSUE TITLE
`lib` folder is missing in version 4.0.0

### ISSUE THREAD

**Issue by ms-tng** [sanack/node-jq#611]
In the package for version 4.0.0 published to NPM, the `main` field in `package.json` refers to `lib/jq.js`, but there is no `lib` folder in the published package.
When importing `const jq = require('node-jq')` as described in the docs, you get an error saying that `lib/jq.js` cannot be found.

**Comment by davesnx** [comment]
Pushed a fix under 4.0.1 (that will eventually be a minor release) with the fix.

Sorry for the trouble.
