### ISSUE TITLE
kill jq.run

### ISSUE THREAD

**Issue by davesnx** [sanack/node-jq#65]
According of https://github.com/sanack/node-jq/issues/64
I wanted to keep the module clean:

```js
const jq = require('node-jq')
jq('.', { "foo": "bar"}) // internally will call run
```

and eventually with the changes talked before:
```js
jq.async === jq.run === jq
```

and `jq.sync` could be the sync operation.

I wanted to maintain the jq.async === jq.run === jq for not breaking any compatibility.

Sounds good @mackermans

**Comment by mackermans** [comment]
Sounds good, we can keep this functionality, deprecate it and then completely remove it when we bump to version `1.0.0`

**Comment by brocoli** [comment]
Please, keep returning an object in require / import, as returning anything else makes it a pain to mock in unit tests.
