### ISSUE TITLE
Escaping of variable names

### ISSUE THREAD

**Issue by lmeyerov** [sanack/node-jq#81]
For the below data and command, I successfully receive a result via `jq-play` and the commandline, but an error from `jq.run()`:

**Data**:
```
{"site":"blah.com","user":["user12","user13","user14","15"]}
```
**Command**:
```
[ . as $x | .user[] | {"user": ., "site": $x.site} ]
```
**Expected output:**
```
[...]
```
**Actual output:**
```
 Error: jq: error: syntax error, unexpected '|', expecting '$' or '[' or '{' (Unix shell quoting issues?) at <top-level>, line 1:
```

If I replace `$` with `\\$`, the error goes away:
```
[ . as \\$x | .user[] | {"user": ., "site": \\$x.site} ]
```
While this is fine in theory, I believe the goal is to conform to `jq`'s syntax, so this is surprising behavior.

**Comment by mackermans** [comment]
@lmeyerov I think this has to do with `node-jq` running `jq` with double-quoted strings, so `$x` is evaluated as shell variable. We will probably have to either escape the dollar signs as you suggested, or swap the double for single quotes.

Thanks for reporting the issue, I'll see to get it fixed soon.

**Comment by davesnx** [comment]
Hey @lmeyerov, can you try now with v0.5.4?
