### ISSUE TITLE
more clear documentation and example

### ISSUE THREAD

**Issue by kahidna** [sanack/node-jq#88]
Hi @davesnx,     
I try learn to processing long json using your node-jq because `JSON.parser` is not able process more than 100 objects. But I have little bit confuse about your syntax example when using string as input. say I have json but in string type :    
`stringJson = '{"menu": {"id": "file","value": "File","popup": {"menuitem": [{"value": "New", "onclick": "CreateNewDoc()"},{"value": "Open", "onclick": "OpenDoc()"},{"value": "Close", "onclick": "CloseDoc()"}]}}}'`    
&nbsp;    
and in your documentation, to process string you said :   
`jq.run('.', '{ foo: "bar" }', { input: 'string' }).then(console.log)`    
&nbsp;     
my question is : where should I put `stringJson` variable into the the part of the code? because `foo` and `bar` is not clear enough for me. I've try to put the variable as `foo`, `bar` or both of them, but the code still not running well.

**Comment by davesnx** [comment]
Hi @kahidna 

Seems that the response that you are asking for is: The second parameter is the JSON that you are accessing, in your example would look like:


`jq.run('.', stringJson, { input: 'string' }).then(console.log)`

**Comment by kahidna** [comment]
wow, cool.  
work like a charm. thank you very much @davesnx :)
