### ISSUE TITLE
No possibility to use --slurp argument

### ISSUE THREAD

**Issue by piotrkochan** [sanack/node-jq#95]
There is no way to use --slurp or any other additional argument

**Comment by davesnx** [comment]
Hey @piotrkochan,

Currently we didn't implement slurp, we didn't found the proper use-case for that.
We could easily add it thought. Could you share what's a good example to add slurp or any other option to node-jq?

Thanks for creating the issue.

**Comment by piotrkochan** [comment]
It is impossible to fetch multiple results as one, real object. Not string:

```json
{
  "something": 1
}
{
  "something": 112
}
```

As:
```json
[
  {
    "something": 1
  }
  {
    "something": 112
  }
]
```

Right now result must be manually parsed in order to detect multiple objects and jq-node will not return object when `{output: 'json'}` is applied: https://github.com/sanack/node-jq/blob/master/src/jq.js#L13
So it's a little bit goofy solution

**Comment by davesnx** [comment]
Cool, thanks. 

I will take a look into a possible solution. I will keep this open until I have something working.

Thanks for the example @piotrkochan

**Comment by piotrkochan** [comment]
How it's going?

**Comment by joshes** [comment]
@davesnx curious if you're already working on a solution or not. i may have some time to look into this if not.

**Comment by davesnx** [comment]
Hey @piotrkochan and @joshes,

Thanks for the interest on this, we did have time to work on it.

@mackermans created this PR 2 days ago and he has something to enable slurp. We will try to merge and release it this week.

This [PR](https://github.com/sanack/node-jq/pull/96) allows `jq` to run with multiple files and another PR enabling slurp will be trivial.

Hope that works for you @joshes.

**Comment by mackermans** [comment]
@piotrkochan @joshes 

I just opened a PR (#97) that adds support for slurp that should resolve your issue. 

Let me know if there are any other additional arguments you would like support for.

**Comment by joshes** [comment]
Thats great! Thanks @mackermans!
